# packages
# install.packages("rJava")
# install.packages("xlsx")
#install.packages("writexl") 
# install.packages("tidyr")
# install.packages("dplyr")
# install.packages("ggplot2")
# install.packages("Hmisc")
# install.packages("corrplot")
# install.packages("PerformanceAnalytics")
# install.packages("sets")
# install.packages("lsr")
# install.packages("MLmetrics")
# install.packages("nortest")
# install.packages("fields")
# #install.packages("foreach")
# install.packages("iterators")
# #install.packages("doSNOW")
# install.packages("doParallel") 
# #install.packages("doMPI")
# install.packages("readr")
#libraries
#Sys.setenv(JAVA_HOME='C:\\Program Files\\Java\\jre-9') # for 64-bit version
#library(rJava)
#library(xlsx)
library(data.table)
library(readr)
library(tidyr)
library(plyr)
library(dplyr)
library(ggplot2)
library(Hmisc)
library(corrplot)
library(PerformanceAnalytics)
library(sets)
library(MLmetrics)
#library(psych)
library(nortest)
library(lsr)
library(fields)
#library(doSNOW)
library(doParallel)
#library(doMPI)
#library(foreach)
library(writexl)


